### ISSUE TITLE
Unexpected questionmark with DML statements in where clause

### ISSUE THREAD

**Issue by rpanic** [darkredz/Zeko-SQL-Builder#21]
Hi,

First up, thanks for creating this library. The DSL is really amazing to work with and makes writing SQL statements a lot easier. 
I started implementing some update and delete statements, and there is a weird issue with the values in the where clause being just a questionmark. 
`UPDATE generic_entity SET test = 'Test1' WHERE test = ?`

A Code which should replicate the issue:
``` kotlin
val sql = Update(GenericEntity().apply { test = "Test1" })
            .where("test" eq "Test2")
            .toSql()

class GenericEntity : Entity {
    constructor(map: Map<String, Any?>) : super(map)
    constructor(vararg props: Pair<String, Any?>) : super(*props)
    var test: String? by map
}
``` 

I imagine this should be some kind of wildcard to parse the actual values in later.I did a bit of debugging and found that the actual value gets thrown away since the eq in sql/operators/declarations is never called with the useRawValue flag set to true. 
Am i missing something here?
Thanks for your help in advance :)

**Comment by darkredz** [comment]
It was design to generate parameterized SQL for Strings, with useRawValue default to false due to SQL injections.  If you really prefer to always use the raw string as opposed to the question mark,
either use the static function call `eq("test", "Test2", true)`

Or you can always override the eq inflix by implementing your own 
```kotlin
// now "test" eq "Test2" will always gives u the String values 
infix fun String.eq(value: String): QueryBlock {
    return io.zeko.db.sql.operators.eq(this, value, true)
}
```

**Comment by rpanic** [comment]
Okay, but shouldn´t the wildcard be replaced by the value at a later point?  When does this happen or does one have to do this themselves?

I also tried manually calling the static function. The problem is that the value-string does not get surrounded by quotes in that case. 

I could of course parse the values in automatically, but I wanted to clarify the general usage of this.

**Comment by darkredz** [comment]
The string value would not be quoted, there are several cases that one would need to compare with different columns/sql functions in the conditions (where the string can't be quoted)
ColumnB = ColumnA
ColumnB = SUM(ColumnA)

So the library leaves it to the user to decide what to do with it, eg. extend it to return a QueryBlock that escaped the string values in this case.

**Comment by rpanic** [comment]
Ah, I didn´t think about that at all... But yeah it makes sense now. I guess I´ll replace the wildcard then.
Seems like a good design choice
Thanks for helping and clearing that up :)

**Comment by darkredz** [comment]
No problem, let me know what could be improved in the future, am closing this issue. now.
