### ISSUE TITLE
Full join support

### ISSUE THREAD

**Issue by marwins** [darkredz/Zeko-SQL-Builder#38]
Hi,

Thanks for this nice library !

Can we add the support for full join, i guess by adding the following lines in Query.kt :
```kotlin
fun fullJoin(table: String): Query {
    tableToJoin["full-join-" + table] = arrayListOf()
    return this
}
```

Sorry, I am not able to push a branch with the feature.

**Comment by darkredz** [comment]
added with commit [938536d12f83081a6752ad73d1e2e4c872d6efda](https://github.com/darkredz/Zeko-SQL-Builder/commit/938536d12f83081a6752ad73d1e2e4c872d6efda)
