### ISSUE TITLE
Trying a way to join on a subquery

### ISSUE THREAD

**Issue by marwins** [darkredz/Zeko-SQL-Builder#39]
Hi,

I try to create a request with a subrequest join.

The best solution I found (even if it's not the perfect one) :
```kotlin
Query().
  fields("...")
  .from("mainTable as main_table")
  .join(
      "(" + Query().fields("...").from("otherTable").toSql() + ") as other_table"
  )
```

The main problem I get with this solution, is when the subquery contains the char `-` (as minus operator for example), I got a wrong query due to the split : https://github.com/darkredz/Zeko-SQL-Builder/blob/157e426f63930628bf32331be751b82fb06341b1/src/main/kotlin/io/zeko/db/sql/QueryPart.kt#L102

Is there a solution that could resolve this issue, should we change the seperator  `-` to something more complex that could not be found in subquery ?

**Comment by darkredz** [comment]
resolved with commit [938536d12f83081a6752ad73d1e2e4c872d6efda](https://github.com/darkredz/Zeko-SQL-Builder/commit/938536d12f83081a6752ad73d1e2e4c872d6efda)

You can now pass a Query instance to join()

```sql
Query().
  fields("...")
  .from("mainTable as main_table")
  .join(
     Query().fields("...").from("other_table"),
     "other_table"
  )
```

See usage in mysql [test case](https://github.com/darkredz/Zeko-SQL-Builder/blob/938536d12f83081a6752ad73d1e2e4c872d6efda/src/test/kotlin/io/zeko/db/sql/MySQLJoinQuerySpec.kt#L137)
