### ISSUE TITLE
Support for INSERT ON DUPLICATE KEY / INSERT IGNORE

### ISSUE THREAD

**Issue by dfontenot** [darkredz/Zeko-SQL-Builder#44]
Hello,

Is there any planned support for INSERT ... ON DUPLICATE KEY IGNORE / UPDATE using the query builder? Or am I missing something in the docs?

Also, thank you for making this great library.

**Comment by darkredz** [comment]
It's available in v1.4.0 with onDuplicateUpdate() and insert() methods
check out example at https://github.com/darkredz/Zeko-SQL-Builder/blob/a70f6d207d77048f690d0d728e22091fe152dda8/src/test/kotlin/io/zeko/db/sql/InsertStatementSpec.kt#L128
